### States for Callback Receiver helper.
### This helper is positioned at a specific location off-screen,
### and wears a very large Clsn2 animation.
### The purpose of this Helper is to be hit by Projectiles generated by
### Spy helpers, for p1stateno.
from mdk.compiler import statedef
from mdk.types import SCOPE_HELPER, MoveType
from mdk.stdlib import ChangeAnim

from source.includes.constants import RECEIVER_HELPER_ID
from source.includes.shared import SendToDevilsEye

RECEIVER_ANIM = 2694500

@statedef(stateno = RECEIVER_HELPER_ID, movetype = MoveType.I, scope = SCOPE_HELPER(RECEIVER_HELPER_ID))
def CallbackReceiver_Actions():
    SendToDevilsEye()

    ChangeAnim(value = RECEIVER_ANIM)
    ## 