### States for Callback Receiver helper.
### This helper is positioned at a specific location off-screen,
### and wears a very large Clsn2 animation.
### The purpose of this Helper is to be hit by Projectiles generated by
### Spy helpers, for p1stateno.
from mdk.compiler import statedef
from mdk.types import SCOPE_HELPER, MoveType, HitAttr, HitType
from mdk.stdlib import ChangeAnim, HitBy, PosSet, root

from source.includes.constants import RECEIVER_HELPER_ID
from source.includes.shared import SendToDevilsEye

from source.anims import CALLBACK_RECEIVER_ANIM

@statedef(stateno = RECEIVER_HELPER_ID, movetype = MoveType.H, scope = SCOPE_HELPER(RECEIVER_HELPER_ID))
def CallbackReceiver_Actions():
    SendToDevilsEye()

    ChangeAnim(value = CALLBACK_RECEIVER_ANIM)
    PosSet(x = root.Pos.x, y = root.Pos.y)
    HitBy(value = (HitType.C, HitAttr.HP))